### ISSUE TITLE
Unknown identifier hook

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metacalc#6]
**Catch access to the unknown identifier**

We can do that because we use `Proxy` as a context for metavm `Script` so we should check identifier:
- In namespaces, for example `Math`
- In `Sheet.expressions`
- In `Sheet.data`
- Otherwise call hook

```js
sheet.on('identifier', (sheet, prop) => {
  const value = 'get value somehow';
  return value;
});
```

**Comment by tshemsedinov** [comment]
@justgowa welcome! You can start implementing this

**Comment by justgowa** [comment]
@tshemsedinov  I tried a few times, but I'm not sure that I'm doing right
